version: '3.9'
services:
  backend:
    build: ./backend
    volumes:
      - ./cookies:/app/cookies
    environment:
      - UPSTASH_REDIS_URL=${UPSTASH_REDIS_URL}
      - UPSTASH_REDIS_TOKEN=${UPSTASH_REDIS_TOKEN}
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
volumes:
  cookies:
